/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCatalogoTabelaRouteImport } from './routes/_app.catalogo-tabela'
import { Route as AppCatalogoRouteImport } from './routes/_app.catalogo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoTabelaRoute = AppCatalogoTabelaRouteImport.update({
  id: '/catalogo-tabela',
  path: '/catalogo-tabela',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof AppCatalogoRoute
  '/catalogo-tabela': typeof AppCatalogoTabelaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/logs': typeof AppLogsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/catalogo': typeof AppCatalogoRoute
  '/catalogo-tabela': typeof AppCatalogoTabelaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/logs': typeof AppLogsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/catalogo': typeof AppCatalogoRoute
  '/_app/catalogo-tabela': typeof AppCatalogoTabelaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/catalogo-tabela'
    | '/configuracoes'
    | '/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/catalogo'
    | '/catalogo-tabela'
    | '/configuracoes'
    | '/logs'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/catalogo'
    | '/_app/catalogo-tabela'
    | '/_app/configuracoes'
    | '/_app/logs'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo-tabela': {
      id: '/_app/catalogo-tabela'
      path: '/catalogo-tabela'
      fullPath: '/catalogo-tabela'
      preLoaderRoute: typeof AppCatalogoTabelaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo': {
      id: '/_app/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppCatalogoTabelaRoute: typeof AppCatalogoTabelaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppLogsRoute: typeof AppLogsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppCatalogoTabelaRoute: AppCatalogoTabelaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppLogsRoute: AppLogsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
